=== okarras/ReqVidA/settings/customannotations.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="customannotations">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="customannotation" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="attributes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="attribute1"/>
                    <xs:element type="xs:string" name="attribute2"/>
                    <xs:element type="xs:string" name="attribute3"/>
                    <xs:element type="xs:string" name="attribute4"/>
                    <xs:element type="xs:string" name="attribute5"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== okarras/ReqVidA/settings/customannotations.xml
<?xml version="1.0" encoding="UTF-8"?>
<customannotations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="customannotations.xsd">

	<customannotation id="Scenario">
		<attributes>
			<attribute1>Description:</attribute1>
			<attribute2></attribute2>
			<attribute3></attribute3>
			<attribute4></attribute4>
			<attribute5></attribute5>
		</attributes>
	</customannotation>

	<customannotation id="Storycard">
		<attributes>
			<attribute1>Title:</attribute1>
			<attribute2>User Story:</attribute2>
			<attribute3>Priority:</attribute3>
			<attribute4>Cost:</attribute4>
			<attribute5>Test:</attribute5>
		</attributes>
	</customannotation>

</customannotations>
