=== okarras/ReqVidA/settings/shortcuts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="shortcuts">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="shortcut" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation>
            <xs:documentation>ImportantAnnotation  RequirementAnnotation  RAW RequirementAnnotation  FUNCTIONAL RequirementAnnotation  NONFUNCTIONAL RequirementAnnotation  USE_CASE RAW RequirementAnnotation  QuestionAnnotation  ConflictAnnotation  CustomAnnotation  CustomAnnotation</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="importantannotation" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="comment"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="requirementannotation" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="comment"/>
                    <xs:element type="xs:string" name="granularity"/>
                    <xs:element type="xs:string" name="displayformat"/>
                    <xs:element type="xs:string" name="requirement"/>
                    <xs:element type="xs:string" name="source"/>
                    <xs:element type="xs:string" name="rationale"/>
                    <xs:element type="xs:string" name="obligation"/>
                    <xs:element type="xs:string" name="priority"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="questionannotation" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="comment"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="conflictannotation" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="comment"/>
                    <xs:element type="xs:string" name="conflict"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="customannotation" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="customannotationid"/>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="comment"/>
                    <xs:element type="xs:string" name="attribute1Value"/>
                    <xs:element type="xs:string" name="attribute2Value"/>
                    <xs:element type="xs:string" name="attribute3Value"/>
                    <xs:element type="xs:string" name="attribute4Value"/>
                    <xs:element type="xs:string" name="attribute5Value"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== okarras/ReqVidA/settings/shortcuts.xml
<?xml version="1.0" encoding="UTF-8"?>
<shortcuts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="shortcuts.xsd">
	<!-- ImportantAnnotation -->
	<shortcut id="F1">
		<importantannotation id="IMPORTANT">
			<name></name>
			<comment></comment>
		</importantannotation>
	</shortcut>

	<!-- RequirementAnnotation -->
	<shortcut id="F2">
		<requirementannotation id="REQUIREMENT">
			<name></name>
			<comment></comment>
			<granularity>FEATURE</granularity>
			<displayformat>TEXT</displayformat>
			<requirement></requirement>
			<source></source>
			<rationale></rationale>
			<obligation>SHALL</obligation>
			<priority>PRIORITY1</priority>
		</requirementannotation>
	</shortcut>

	<!-- RAW RequirementAnnotation -->
	<shortcut id="F3">
		<requirementannotation id="REQUIREMENT">
			<name></name>
			<comment></comment>
			<granularity>RAW_REQUIREMENT</granularity>
			<displayformat>TEXT</displayformat>
			<requirement></requirement>
			<source></source>
			<rationale></rationale>
			<obligation>SHALL</obligation>
			<priority>PRIORITY1</priority>
		</requirementannotation>
	</shortcut>

	<!-- FUNCTIONAL RequirementAnnotation -->
	<shortcut id="F4">
		<requirementannotation id="REQUIREMENT">
			<name></name>
			<comment></comment>
			<granularity>FUNCTIONAL_REQUIREMENT</granularity>
			<displayformat>TEXT</displayformat>
			<requirement></requirement>
			<source></source>
			<rationale></rationale>
			<obligation>SHALL</obligation>
			<priority>PRIORITY1</priority>
		</requirementannotation>
	</shortcut>

	<!-- NONFUNCTIONAL RequirementAnnotation -->
	<shortcut id="F5">
		<requirementannotation id="REQUIREMENT">
			<name></name>
			<comment></comment>
			<granularity>NONFUNCTIONAL_REQUIREMENT</granularity>
			<displayformat>TEXT</displayformat>
			<requirement></requirement>
			<source></source>
			<rationale></rationale>
			<obligation>SHALL</obligation>
			<priority>PRIORITY1</priority>
		</requirementannotation>
	</shortcut>

	<!-- USE_CASE RAW RequirementAnnotation -->
	<shortcut id="F6">
		<requirementannotation id="REQUIREMENT">
			<name></name>
			<comment></comment>
			<granularity>RAW_REQUIREMENT</granularity>
			<displayformat>USE_CASE</displayformat>
			<requirement></requirement>
			<source></source>
			<rationale></rationale>
			<obligation>SHALL</obligation>
			<priority>PRIORITY1</priority>
		</requirementannotation>
	</shortcut>

	<!-- QuestionAnnotation -->
	<shortcut id="F7">
		<questionannotation id="QUESTION">
			<name></name>
			<comment></comment>
		</questionannotation>
	</shortcut>

	<!-- ConflictAnnotation -->
	<shortcut id="F8">
		<conflictannotation id="CONFLICT">
			<name></name>
			<comment></comment>
			<conflict></conflict>
		</conflictannotation>
	</shortcut>

	<!-- CustomAnnotation -->
	<shortcut id="F9">
		<customannotation id="CUSTOM">
			<customannotationid>Scenario</customannotationid>
			<name></name>
			<comment></comment>
			<attribute1Value></attribute1Value>
			<attribute2Value></attribute2Value>
			<attribute3Value></attribute3Value>
			<attribute4Value></attribute4Value>
			<attribute5Value></attribute5Value>
		</customannotation>
	</shortcut>

	<!-- CustomAnnotation -->
	<shortcut id="F10">
		<customannotation id="CUSTOM">
			<customannotationid>Storycard</customannotationid>
			<name></name>
			<comment></comment>
			<attribute1Value></attribute1Value>
			<attribute2Value></attribute2Value>
			<attribute3Value></attribute3Value>
			<attribute4Value></attribute4Value>
			<attribute5Value></attribute5Value>
		</customannotation>
	</shortcut>

</shortcuts>
